{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "d7cecf0f-1b88-4928-b408-86fecd36877c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "from datetime import date\n",
    "\n",
    "st.title(\"Conditional Multi-Question Form\")\n",
    "\n",
    "# Initialize the 'answers' dictionary in session_state if it doesn't exist\n",
    "if 'answers' not in st.session_state:\n",
    "    st.session_state['answers'] = {}\n",
    "\n",
    "# Function to save answers after submission\n",
    "def save_answers(q_dict):\n",
    "    st.session_state['answers'] = q_dict\n",
    "    st.success(\"Form submitted successfully!\")\n",
    "    st.json(st.session_state['answers'])\n",
    "\n",
    "# Create the form\n",
    "with st.form(\"my_form\"):\n",
    "\n",
    "    # Temporary dictionary to store this session's answers\n",
    "    answers = {}\n",
    "\n",
    "    # Q1: Radio\n",
    "    q1 = st.radio(\"Q1: Choose an option:\", [\"Option A\", \"Option B\"])\n",
    "    answers['Q1'] = q1\n",
    "\n",
    "    # Q2: Multiple choice + Other\n",
    "    q2_options = [\"Choice 1\", \"Choice 2\", \"Other\"]\n",
    "    q2 = st.multiselect(\"Q2: Select one or more options:\", q2_options)\n",
    "    answers['Q2'] = q2\n",
    "    if \"Other\" in q2:\n",
    "        q2_other = st.text_input(\"Please specify:\")\n",
    "        answers['Q2_other'] = q2_other\n",
    "\n",
    "    # Q3: Select from list\n",
    "    q3_list = [f\"Item {i}\" for i in range(1, 51)]\n",
    "    q3 = st.selectbox(\"Q3: Select an item from the list:\", q3_list)\n",
    "    answers['Q3'] = q3\n",
    "\n",
    "    # Q4: Date range\n",
    "    start_date, end_date = st.date_input(\"Q4: Select date range:\", \n",
    "                                         value=(date.today(), date.today()))\n",
    "    answers['Q4_start'] = start_date\n",
    "    answers['Q4_end'] = end_date\n",
    "\n",
    "    # Q5: Conditional\n",
    "    if q1 == \"Option A\":\n",
    "        q5 = st.text_input(\"Q5: Tell us about topic A\")\n",
    "    else:\n",
    "        q5 = st.text_input(\"Q5: Tell us about topic B\")\n",
    "    answers['Q5'] = q5\n",
    "\n",
    "    # Q6: Depends on Q5\n",
    "    q6 = st.text_area(\"Q6: Additional info based on your previous answer\")\n",
    "    answers['Q6'] = q6\n",
    "\n",
    "    # Q7: Conditional\n",
    "    q7 = st.radio(\"Q7: Choose one for next questions:\", [\"Option A\", \"Option B\"])\n",
    "    answers['Q7'] = q7\n",
    "\n",
    "    # Q8-Q10: Conditional depending on Q7\n",
    "    if q7 == \"Option A\":\n",
    "        q8 = st.text_input(\"Q8: Topic A1\")\n",
    "        q9 = st.text_input(\"Q9: Topic A2\")\n",
    "        q10 = st.text_input(\"Q10: Topic A3\")\n",
    "        answers['Q8'] = q8\n",
    "        answers['Q9'] = q9\n",
    "        answers['Q10'] = q10\n",
    "    else:\n",
    "        q8 = st.text_input(\"Q8: Topic B1\")\n",
    "        answers['Q8'] = q8\n",
    "\n",
    "    # Submit button\n",
    "    submitted = st.form_submit_button(\"Submit\")\n",
    "    if submitted:\n",
    "        save_answers(answers)\n",
    "\n",
    "        # Optionally save to CSV\n",
    "        df = pd.DataFrame([st.session_state['answers']])\n",
    "        df.to_csv(\"responses.csv\", index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "9dc0aa1f-d0da-4124-92bc-ffbbbd8e8c98",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
